#!/bin/sh

export JAVA_HOME=/usr/java/jdk1.8.0_191-amd64
export JAVA_BIN=/usr/java/jdk1.8.0_191-amd64/bin
export PATH=$PATH:$JAVA_HOME/bin
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
export JAVA_HOME JAVA_BIN PATH CLASSPATH

ELASTICSEARCH_HOME=/data/elasticsearch/
ELASTICSEARCH_USER=elastic

case "$1" in
start)
    su $ELASTICSEARCH_USER<<!
    cd $ELASTICSEARCH_HOME
    ./bin/elasticsearch -d
!
    echo "elasticsearch startup"
    ;;  
stop)
    PID=`ps -aux |grep java|grep elasticsearch|awk '{print $2}'` 2>/dev/null
    kill -9 $PID 1>/dev/null 2>&1
    echo "elasticsearch stopped"
    ;;  
restart)
    PID=`ps -aux |grep java|grep elasticsearch|awk '{print $2}'` 2>/dev/null
    kill -9 $PID 1>/dev/null 2>&1
    echo "elasticsearch stopped"
    su $ELASTICSEARCH_USER<<!
    cd $ELASTICSEARCH_HOME
    ./bin/elasticsearch -d
!
    echo "elasticsearch startup"
    ;;    
esac
