#!/bin/sh
PROGRAM=logstash
CONF=logstash.conf
PROGRAM_HOME=/data/$PROGRAM
PROGRAM_CONF=$PROGRAM_HOME/config/$CONF
PROGRAM_LOG=$PROGRAM_HOME/logs

case "$1" in
start)
    $PROGRAM_HOME/bin/$PROGRAM -f $PROGRAM_CONF >/dev/null 2>&1 &
    echo "$PROGRAM startup"
    ;;  
stop)
    PID=`ps -aux |grep java|grep $PROGRAM|grep -v grep|awk '{print $2}'` 2>/dev/null
    kill -9 $PID 1>/dev/null 2>&1
    echo "$PROGRAM stopped"
    ;;  
restart)
    PID=`ps -aux |grep java|grep $PROGRAM|grep -v grep|awk '{print $2}'` 2>/dev/null
    kill -9 $PID 1>/dev/null 2>&1
    echo "$PROGRAM stopped"
    $PROGRAM_HOME/bin/$PROGRAM -f $PROGRAM_CONF >/dev/null 2>&1 &
    echo "$PROGRAM startup"
    ;;    
esac
