metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
fields:
  group: 人脸识别
  server: 入口26.88
fields_under_root: true
output.elasticsearch:
  hosts: ["host1:9200","host2:9200"]

#output.logstash:
  #hosts: ["host1:5044","host2:5044"]
